name: Update Outside Collaborators

on:
  push:
    branches:
    - 'master'
    paths:
    - "groups/*.yml"
    - "groups/*.yaml"
    - "repos/*.yml"
    - "repos/*.yaml"
  workflow_dispatch:

jobs:
  Update:
    name: "Update"
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo gem install octokit yaml
      - name: Set Env Variables
        run: |
          echo "OUTSIDE_COLLABORATORS_GITHUB_ORG=${{ github.repository_owner }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_TOKEN=${{ secrets.OUTSIDE_COLLABORATORS_TOKEN }}" >> ${GITHUB_ENV}
      - uses: actions/checkout@master
      - name: Run Handler
        run: |
          cd scripts
          ./outside-collaborators-handler.rb
      